
== Requirements

* Android Studio 4.2.2
* Java 8

== Setup

The data-donation-sdk KMP project requires the iOSCryptoDD Xcode project to work.
The iOSCryptoDD is a wrapper to use the CryptoSwift library and the project only implements the necessary encrypt/decrypt function for the AESGCM encryption which is used in the KMP project.
The iOSCryptoDD is added as a gradle module to pre-build the Xcode project before the KMP one, its done by the `iOSCryptoDD/build.gradle.kts`.
It's wired to the KMP lib using a native interop bridge, see: `data-donation-sdk/src/nativeInterop/cinterop/iOSCryptoDD.def` & `data-donation-sdk/build.gradle.kts`

_Note:_ Altho' everything is automatic sometimes when changing the `iOSCryptoDD` project it is required to build the cinterop headers with `./gradlew cinteropIOSCryptoDDIosArm64 cinteropIOSCryptoDDIosX64`.

== Release

We are using a custom maven publish plugin to distribute the library using the Github Package repo.
To release a new release version just push a new tag with the format `v[0-9]+.[0-9]+.[0-9]+.`.
Every feature branch is automatically released to the `https://github.com/d4l-data4life/maven-features` repository.
