name: DD-SDK Native CI Android

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - master
      - release/*
  pull_request:
    paths-ignore:
      - 'docs/**'
    branches:
      - master
      - release/*
      - feature/*
      - bugfix/*

jobs:
  build:

    runs-on: [self-hosted, macos]

    env:
      PACKAGE_REGISTRY_TOKEN: ${{ secrets.PACKAGE_REGISTRY_TOKEN }}
      PACKAGE_REGISTRY_USERNAME: ${{ secrets.PACKAGE_REGISTRY_USERNAME }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1.0.3
        id: cache-gradle
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Run android tests 
        run: ./gradlew test
      #- name: Run ios tests 
        #run: ./gradlew iosWithLinkerTest
        #run: ./gradlew iosX64test