name: D4L CI - Pull-Request Validation

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - main
      - release/*
      - feature/*
      - bugfix/*

jobs:
  pull-request-validation:

    runs-on: [self-hosted, macos]

    env:
      PACKAGE_REGISTRY_USERNAME: ${{ secrets.PACKAGE_REGISTRY_USERNAME }}
      PACKAGE_REGISTRY_TOKEN: ${{ secrets.PACKAGE_REGISTRY_TOKEN }}

    steps:
      - name: Display runner context
        run: hostname -s
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Cleanup
        run: ./gradlew clean
      - name: Version
        run: ./gradlew versionInfo
      - name: Build ObjC Crypto library
        run: ./gradlew buildCryptoLibraries
      - name: Build
        run: ./gradlew build
      - name: Publish Feature to Maven Repo
        run: ./gradlew publishFeature
