name: D4L CI - Pull-Request Validation

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - main
      - release/*
      - feature/*
      - bugfix/*
  workflow_dispatch:

jobs:
  pull-request-validation:

    runs-on: macos-latest

    concurrency:
      group: validation-${{ github.head_ref }}
      cancel-in-progress: true

    env:
      PACKAGE_REGISTRY_DOWNLOAD_USERNAME: ${{ secrets.PACKAGE_REGISTRY_DOWNLOAD_USERNAME }}
      PACKAGE_REGISTRY_DOWNLOAD_TOKEN: ${{ secrets.PACKAGE_REGISTRY_DOWNLOAD_TOKEN }}
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_USERNAME }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Cleanup
        run: ./gradlew clean
      - name: Version
        run: ./gradlew versionInfo
      - name: Build
        run: ./gradlew build
      - name: Reset iOS Simulators
        run: xcrun simctl erase all
      - name: Run Swift tests
        run: xcodebuild -project DataDonationCryptoObjC/DataDonationCryptoObjC.xcodeproj -scheme DataDonationCryptoHostApp -sdk iphonesimulator -destination "name=iPhone 12" -derivedDataPath build/DataDonationCryptoObjC test
      - name: Publish Feature to Maven Repo
        run: ./gradlew publishFeature
